### PR TITLE
Fix for Swift PM error #22

### PR DESCRIPTION
**Pull request by Saik0s**
**Issue:** [Link](https://github.com/carambalabs/xcodeproj/issues/22)

### CODE REVIEW

**Comment by pepibumur** [comment]
Nice contribution @Saik0s. It seems that Travis-CI is failing with the changes. Could you have a look? After that it should be ready to be merged.

**Comment by pepibumur** [comment]
@Saik0s I wouldn't update it to Swift 4 until it gets officially announced and all the dependencies support it. Have you tried just updating the `swift-tools-version` line in the `Package.swift` to be:

```
// swift-tools-version:4.0
```

With that, and keeping the version of Swift as 3 should work.

**Comment by Saik0s** [comment]
Your `Package.swift` already has `// swift-tools-version:4.0` and there is no problem with it. If you are talking about my `Package.swift` - I'm using your latest release and just wanted to help you with swift 4 migration(thought this branch is for migration). I was not expecting you to release swift4 version before official release, you just asked me to have a look at Travis' fail, and I tried to fix this issue.

**Comment by pepibumur** [comment]
Hi, @Saik0s, sorry for the misunderstanding, for some reason I thought the swift-tools were still 3.1. It'd be great to have the branch ready to officially merge it when Swift 4 comes out. Regarding Travis-CI, I think one of the dependencies, `Spectre` *(which is not a direct dependency of xcodeproj)* is not Swift 4 compatible.  Spectre is a dependency of [PathKit](https://github.com/kylef/PathKit/blob/master/Package.swift) which doesn't seem to have a Swift 4 compatible version. 

We could start by adding support to that library and then point our dependency to that branch. I can help you do that migration. Swift 4 is almost here! 🎉

**Comment by artemnovichkov** [comment]
I guess I've fixed it in #84.

**Comment by pepibumur** [comment]
Yes @artemnovichkov. We can close this one.

**Pull request closed without merging**
